<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_55776bdb8cf24',
	'title' => 'Field Group for Chef\'s Training Sessions',
	'fields' => array (
		array (
			'key' => 'field_54368ffcf09ea',
			'label' => 'Chef\'s Training Sessions',
			'name' => 'training_sessions',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'row_min' => '',
			'row_limit' => '',
			'layout' => 'row',
			'button_label' => 'Add Session',
			'min' => 0,
			'max' => 0,
			'sub_fields' => array (
				array (
					'key' => 'field_543690feb2cd1',
					'label' => 'Which Session?',
					'name' => 'which_session',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Part-Time' => 'Part-Time',
						'Full-Time' => 'Full-Time',
					),
					'default_value' => array (
						'' => '',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_54369017f09eb',
					'label' => 'Start Date of Session',
					'name' => 'start_date_of_session',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'first_day' => 1,
					'return_format' => 'Ymd',
					'display_format' => 'F d, Y',
				),
				array (
					'key' => 'field_54369034f09ec',
					'label' => 'Times, Monday to Thursday',
					'name' => 'times,_monday_to_thursday',
					'type' => 'text',
					'instructions' => 'Please use an em dash.',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_543690feb2cd1',
								'operator' => '==',
								'value' => 'Full-Time',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '9 am — 4 pm',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_54369055f09ed',
					'label' => 'Times, Friday',
					'name' => 'times,_friday',
					'type' => 'text',
					'instructions' => 'Please use an em dash.',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_543690feb2cd1',
								'operator' => '==',
								'value' => 'Full-Time',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '9 am — 1 pm',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_543691d571fca',
					'label' => 'Schedule',
					'name' => 'schedule',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_543690feb2cd1',
								'operator' => '==',
								'value' => 'Part-Time',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'row_min' => '',
					'row_limit' => '',
					'layout' => 'row',
					'button_label' => 'Add Row',
					'min' => 0,
					'max' => 0,
					'sub_fields' => array (
						array (
							'key' => 'field_54369309bad78',
							'label' => 'Day(s)',
							'name' => 'day',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'i.e., "Monday," etc.',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_543691eb71fcb',
							'label' => 'Times',
							'name' => 'times',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Please use em dashes.',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'collapsed' => '',
				),
			),
			'collapsed' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'options-page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'custom_fields',
		3 => 'discussion',
		4 => 'comments',
		5 => 'author',
		6 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_55776bdc1dd54',
	'title' => 'Field Group for Upcoming Open Houses',
	'fields' => array (
		array (
			'key' => 'field_5435d183d5b2c',
			'label' => 'Open House Date',
			'name' => 'open_house_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'first_day' => 1,
			'return_format' => 'Ymd',
			'display_format' => 'F d, Y',
		),
		array (
			'key' => 'field_5435d1a3d5b2d',
			'label' => 'Open House Time',
			'name' => 'open_house_time',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '6pm',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'options-page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;